server:
  port: 9004
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://10.2.54.42:8761/eureka
spring:
  application:
    name: user-server