server:
  port: 9007
spring:
  application:
    name: feign-server
# 启动feign的容错机制
feign:
 hystrix:
  enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://master:8761/eureka/,http://slave:8761/eureka/