spring:
  application:
    name: hystrix-server
server:
  port: 9009
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://master:8761/eureka/,http://slave:8761/eureka/