server:
  port: 8761
eureka:
  instance:
    hostname: master
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://slave:8761/eureka
spring:
  application:
    name: eureka-server