server:
  port: 9005
spring:
  application:
    name: order-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://10.2.54.42:8761/eureka