server:
  port: 9005
spring:
  application:
    name: order-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://master:8761/eureka/,http://slave:8761/eureka/